const REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bOuestion/gi, "Question"],
  [/\bServoeNow\b/gi, "ServiceNow"],
  [/\bServicenow\b/gi, "ServiceNow"],
  [/\bAdminisirsior\b/gi, "Administrator"],
  [/\bAdminisirator\b/gi, "Administrator"],
  [/\bDicovry\b/gi, "Discovery"],
  [/\bAdin\b/gi, "Admin"],
  [/\bWorkspco\b/gi, "Workspace"],
  [/\bWorkspae\b/gi, "Workspace"],
  [/\bContuaton\b/gi, "Configuration"],
  [/\bContuin\b/gi, "Configuration"],
  [/\bCHD\b/g, "CMDB"],
  [/\bCHDB\b/g, "CMDB"],
  [/\bWDB\b/g, "CMDB"],
  [/\bCis\b/g, "CIs"],
  [/\bCIS\b/g, "CIs"],
  [/\baluibutes\b/gi, "attributes"],
  [/\batribu(?:te|tes)\b/gi, "attributes"],
  [/\blems\b/gi, "items"],
  [/\bduplcatio\b/gi, "deduplication"],
  [/\bde-cupicaton\b/gi, "deduplication"],
  [/\bRoconcilion\b/gi, "Reconciliation"],
  [/\bCertifcaion\b/gi, "Certification"],
  [/\bEnd of ie\b/gi, "End of Life"],
  [/\bEnd of life\b/gi, "End of Life"],
  [/\bCMDB Dota\b/gi, "CMDB Data"],
  [/\bPorm Owner\b/gi, "Form Owner"],
  [/\bConfiguration Manage\b/gi, "Configuration Manager"],
  [/\bContain Manager\b/gi, "Configuration Manager"],
  [/\bContuaton Manage\b/gi, "Configuration Manager"],
  [/\bUnified Map\b/gi, "Unified Map"],
  [/\bService Owner\b/gi, "Service Owner"],
  [/\bHealth Dashboard\b/gi, "Health Dashboard"],
  [/\bGraph Connector\b/gi, "Graph Connector"],
  [/\bQuestion(\d+)of(\d+)/gi, "Question $1 of $2"],
  [/\bQuestion(\d+)o([lfIl1])(\d+)/gi, "Question $1 of $3"],
  [/\bQuestion(\d+)\s+o\s*(\d+)/gi, "Question $1 of $2"],
  [/\bQuestion\s*(\d+)\s*of\s*(\d+)/gi, "Question $1 of $2"],
  [/\b([A-D])\s*\.\s*beete\b/gi, "$1. Delete"],
  [/\b([A-D])\s*\.\s*Acewan\b/gi, "$1. Archive"],
  [/\b([A-D])\s*\.\s*Acne\b/gi, "$1. Archive"],
  [/\b([A-D])\s*\.\s*Rete\b/gi, "$1. Retire"],
  [/\bTool box\b/gi, "Toolbox"],
  [/\bChoose 2cptons\b/gi, "Choose 2 options"],
  [/\bChoose 2 options\b/gi, "Choose 2 options"],
  [/\bChoose option\b/gi, "Choose option"],
  [/\bCMDB 360\b/g, "CMDB 360"],
  [/\bService Mapping\b/gi, "Service Mapping"],
  [/\bDiscovery Admin\b/gi, "Discovery Admin"],
];

export function normalizeOcrText(raw: string): string {
  let text = raw.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  for (const [pattern, replacement] of REPLACEMENTS) {
    text = text.replace(pattern, replacement);
  }
  return text;
}
